### ISSUE TITLE
harmonize ~_loadImages() functions

### ISSUE THREAD

**Issue by jonathancallahan** [MazamaScience/TBCellGrowth#4]
Right now there are two ~_loadImages() functions with similar arguments:

`solid_loadImages <- function(dataDir, xy, channels=c("c1"), channelNames=c("phase"), ext="tif", start=1, n=NA)`

`flow_loadImages <- function(dir, ext="tiff", n=NA, start=1)`

There are several inconsistencies between them:
- `dataDir` vs. `dir`
- `ext="tif"` vs. `ext="tiff"` 
- `start=1, n=NA` vs. `n=NA, start=1`

It may be the case that the flow_ and solid_ experiments have enough differences that we need two separate loadImages() functions. But we should make every effort to provide as uniform an API as possible by at least using the same argument names in the same order and with the same defaults.

**Comment by procterw** [comment]
One thing worth noting is that the flow_loadImages function is (likely) temporary and they will eventually be merged. My impression is that the files loaded with flow_loadImages are in a simplified file structure, whereas the "solid" images are in the actual raw structure. I'll need to ask Kyle about this to get a sense of where to go.

**Comment by procterw** [comment]
For now I've made the arguments more consistent but this will have to be revisited soon.
