### ISSUE TITLE
"Analysis" section

### ISSUE THREAD

**Issue by procterw** [MazamaScience/TBCellGrowth#5]
> Can you include an "analysis" section?  For phase contrast images it would be great to have the slope of the line and the derived doubling time included in the output table.  This would require reading the time time point signature out of the meta-data or file name.  For the fluorescent channels, a calculation such as "percent of phase contrast image that is fluorescent" would be similarly useful.

This will likely be a new CSV file with the mentioned analysis.

**Comment by jonathancallahan** [comment]
This is starting to remind me of the organization in use with the PM2.5 monitoring data. There we have a data file that is organized as "time X site" with sites as columns. We also have a metadata file with "site X attribute". Note that "site" is used as the column name in data file but as row name in the metadata file

In Kyle's case I think it would be less confusing for our end user if the metadata file were organized with sites as column names and rows containing attributes such as slope, doubling time, first appearance, maximum size, etc., etc.

This gives us a way to add any future requests to this same "colony metadata" file.

**Comment by jonathancallahan** [comment]
Out of scope for the current release.
